export const formLabels = {
  meta: {
    section: "Dane podstawowe",
    date: "Data",
    time: "Godzina",
    place: "Miejsce",
    present: "Inne osoby obecne"
  },
  simple: {
    section: "Opis sytuacji",
    factDescription: "Krótki opis sytuacji",
    antecedents: "Co wydarzyło się tuż przed?",
    signals: "Jakie były pierwsze sygnały napięcia?",
    interventions: "Jak zareagowano na pierwsze sygnały?",
    behavior: "Co było widoczne w zachowaniu?",
    risk: "Co było najbardziej ryzykowne albo najtrudniejsze?",
    helped: "Co pomogło obniżyć napięcie lub uspokoić sytuację?",
    notes: "Dodatkowe uwagi"
  },
  incident: {
    baselineSection: "0. Poziom bazowy i kontekst dnia",
    beforeSection: "1. Bezpośrednio przed zdarzeniem",
    expectationsSection: "2. Czego oczekiwano w tym momencie?",
    signalsSection: "3. Pierwsze oznaki narastającego napięcia",
    actionsSection: "3A. Faza napięcia i 4. Działania",
    behaviorSection: "5. Opis zachowania",
    afterSection: "6. Co wydarzyło się po zdarzeniu?",
    physicalSection: "6A. Interwencja fizyczna",
    regulationSection: "7-9. Regulacja i wpływ na napięcie",
    tension: "Poziom napięcia",
    tired: "Zmęczenie / senność",
    slept: "Sen / odpoczynek w ciągu dnia",
    sleepDetails: "O której i jak długo?",
    stayStage: "Etap tygodnia / pobytu",
    stayStageLoad: "Czy etap był obciążający?",
    burdens: "Czynniki obciążające",
    burdensOther: "Jeśli inne, wpisz jakie",
    antecedents: "Co działo się do 5 minut przed?",
    factDescription: "Krótki opis sytuacji (fakty, bez interpretacji)",
    expectations: "Oczekiwania",
    expectationOther: "Jeśli inne, wpisz jakie",
    signalsAppeared: "Czy pojawiły się sygnały?",
    signals: "Jakie sygnały?",
    signalsOther: "Jeśli inne, wpisz jakie",
    timeToEscalation: "Ile czasu przed eskalacją?",
    firstSignal: "Co zwykle pojawia się najpierw?",
    predicts: "Czy zapowiada trudniejsze zachowanie?",
    phase: "W jakiej fazie napięcia była osoba?",
    interventions: "Działania podjęte przed eskalacją",
    interventionDetails: "Jeśli inne, wpisz jakie",
    unconditional: "Dostępne bez warunku?",
    usedRegulator: "Czy skorzystał(a)?",
    reducedTension: "Czy obniżyło napięcie?",
    earlierPossible: "Można było zareagować wcześniej?",
    earlierWhat: "Co było możliwe?",
    behavior: "Opis zachowania",
    intensity: "Intensywność",
    escalationDuration: "Czas trwania eskalacji",
    harms: "Czy doszło do",
    after: "Co wydarzyło się po zdarzeniu?",
    afterOther: "Jeśli inne, wpisz jakie",
    calmTime: "Czas do pełnego uspokojenia",
    physicalThisWeek: "Interwencja fizyczna w tym tygodniu?",
    physicalCount: "Ile razy?",
    lowerThreshold: "Niższy próg / szybsza reakcja?",
    physicalNote: "Notatka o interwencji fizycznej",
    endedBy: "Co najbardziej pomogło w tej sytuacji?",
    endedByOther: "Jeśli inne, wpisz jakie",
    worsened: "Co mogło nasilić napięcie?",
    regulators: "Co pomogło obniżyć napięcie?",
    rewards: "Co podtrzymywało wykonywanie aktywności mimo napięcia?"
  },
  map: {
    section: "Mapa środowiska",
    places: "Miejsca i aktywności",
    preferred: "Chętnie przebywa w",
    avoided: "Unika / wychodzi z trudem z",
    likes: "Najchętniej angażuje się w",
    easiestWhen: "Najłatwiej funkcjonuje, gdy",
    cooperatesWith: "Najłatwiej współpracuje z",
    reducers: "Co obniża napięcie?",
    dependsOn: "Zachowanie zmienia się w zależności od",
    dependsDescription: "Opis zależności",
    escalationContexts: "Najczęstsze sytuacje eskalacji",
    escalationOther: "Jeśli inne, wpisz jakie",
    noAggression: "Czy są sytuacje bez agresji?",
    noAggressionWhere: "Jakie?",
    placeColumn: "Miejsce",
    timeColumn: "Czas",
    activityColumn: "Rodzaj aktywności"
  }
};
