export const formLabels = {
  meta: {
    section: "Dane podstawowe",
    date: "Data",
    time: "Godzina",
    place: "Miejsce",
    present: "Inne osoby obecne"
  },
  simple: {
    section: "Opis sytuacji",
    antecedents: "Co wydarzyło się tuż przed?",
    signals: "Jakie były pierwsze sygnały napięcia?",
    interventions: "Jak zareagowano na pierwsze sygnały?",
    behavior: "Jaki był przebieg sytuacji i co można było zaobserwować?",
    helped: "Co pomogło obniżyć napięcie lub wyregulować sytuację?",
    notes: "Na co dziecko/uczeń miało wpływ, a na co nie?"
  },
  incident: {
    baselineSection: "0. Poziom bazowy i kontekst dnia",
    beforeSection: "1. Bezpośrednio przed zdarzeniem",
    expectationsSection: "2. Czego oczekiwano w tym momencie?",
    signalsSection: "3. Pierwsze oznaki narastającego napięcia",
    actionsSection: "3A. Faza napięcia i 4. Działania",
    behaviorSection: "5. Opis zachowania",
    afterSection: "6. Co wydarzyło się po zdarzeniu?",
    physicalSection: "6A. Interwencja fizyczna",
    regulationSection: "7-9. Regulacja i wpływ na napięcie",
    tension: "Poziom napięcia przed zdarzeniem",
    tired: "Zmęczenie / senność",
    slept: "Sen / odpoczynek w ciągu dnia",
    sleepDetails: "O której i jak długo?",
    stayStage: "Etap tygodnia / pobytu",
    stayStageLoad: "Czy etap był obciążający?",
    burdens: "Czynniki obciążające",
    burdensOther: "Jeśli inne, wpisz jakie",
    bodyState: "Stan ciała przed zdarzeniem",
    bodyStateOther: "Jeśli inne, wpisz jakie",
    sensoryIntensity: "Intensywność bodźców w środowisku",
    sensoryIntensityOther: "Jeśli inne, wpisz jakie",
    antecedents: "Co działo się do 5 minut przed?",
    factDescription: "Doprecyzowanie tego, co było bezpośrednio przed",
    predictability: "Przewidywalność sytuacji",
    expectations: "Oczekiwania",
    expectationOther: "Jeśli inne, wpisz jakie",
    influence: "Na co dziecko miało wpływ w tym momencie?",
    noInfluence: "Na co dziecko NIE miało wpływu?",
    signalsAppeared: "Czy pojawiły się sygnały?",
    activationSignals: "Typ 1: Aktywacja (sympatyczny)",
    activationSignalsOther: "Jeśli inne, wpisz jakie",
    shutdownSignals: "Typ 2: Shutdown (parasympatyczny/freeze)",
    shutdownSignalsOther: "Jeśli inne, wpisz jakie",
    sensorySignals: "Typ 3: Sensoryczny",
    sensorySignalsOther: "Jeśli inne, wpisz jakie",
    timeToEscalation: "Ile czasu przed eskalacją?",
    firstSignal: "Co zwykle pojawia się najpierw?",
    predicts: "Czy zapowiada trudniejsze zachowanie?",
    phase: "Faza napięcia w momencie podjęcia działań",
    interventions: "Działania podjęte przed eskalacją",
    interventionDetails: "Jeśli inne, wpisz jakie",
    unconditional: "Czy pomoc/interwencja była dostępna od razu, bez wcześniejszego uspokojenia się, wykonania polecenia lub spełnienia wymagania?",
    usedRegulator: "Czy skorzystał(a)?",
    reducedTension: "Czy działanie pomogło na tym etapie?",
    earlierWhat: "Co ta sytuacja pokazuje jako wskazówkę na przyszłość?",
    behavior: "Opis zachowania",
    intensity: "Intensywność zachowania",
    escalationDuration: "Czas trwania eskalacji",
    harms: "Czy doszło do",
    after: "Co wydarzyło się po zdarzeniu?",
    afterOther: "Jeśli inne, wpisz jakie",
    calmTime: "Czas do pełnego uspokojenia emocjonalnego",
    cognitiveRecoveryTime: "Czas do odzyskania dostępności poznawczej",
    physicalThisWeek: "Interwencja fizyczna w tym tygodniu?",
    physicalCount: "Ile razy?",
    lowerThreshold: "Czy dziecko/uczeń reagowało szybciej lub mocniej niż zwykle?",
    physicalNote: "Notatka o interwencji fizycznej",
    endedBy: "Co najbardziej pomogło zakończyć eskalację?",
    endedByOther: "Jeśli inne, wpisz jakie",
    worsened: "Co mogło nasilić napięcie?",
    rewards: "Co pozwoliło dziecku kontynuować aktywność przed eskalacją mimo narastającego napięcia?",
    rewardsOther: "Jeśli inne, wpisz jakie"
  },
  map: {
    section: "Mapa środowiska",
    places: "Miejsca i aktywności",
    preferred: "Chętnie przebywa w",
    avoided: "Unika / wychodzi z trudem z",
    likes: "Najchętniej angażuje się w",
    easiestWhen: "Najłatwiej funkcjonuje, gdy",
    cooperatesWith: "Najłatwiej współpracuje z",
    reducers: "Co obniża napięcie?",
    dependsOn: "Zachowanie zmienia się w zależności od",
    dependsDescription: "Opis zależności",
    escalationContexts: "Najczęstsze sytuacje eskalacji",
    escalationOther: "Jeśli inne, wpisz jakie",
    noAggression: "Czy są sytuacje bez agresji?",
    noAggressionWhere: "Jakie?",
    placeColumn: "Miejsce",
    timeColumn: "Czas",
    activityColumn: "Rodzaj aktywności"
  }
};
