name: deploy ongoing-monitoring

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "*"
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: install dependencies
        run: npm ci

      - name: build website
        run: npm run build

      - name: rsync website content
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./dist/
          remote_path: ${{ secrets.SITE_REMOTE_PATH }}/ongoing-monitoring/
          remote_host: ${{ secrets.SITE_REMOTE_HOST }}
          remote_user: ${{ secrets.SITE_REMOTE_USER }}
          remote_port: ${{ secrets.SITE_REMOTE_PORT }}
          remote_key: ${{ secrets.SITE_DEPLOYMENT_KEY }}
